### ISSUE TITLE
Update entity objects

### ISSUE THREAD

**Issue by bonganiTM** [Buhle8/microservices#3]
-Add table name on your entity. e.g. @Table(name = "cars").
- Annotate your attributes with @Column(name = "vin")
- Move your unique attribute to the top.

![image](https://github.com/Buhle8/microservices/assets/157486265/aed1e272-e14f-4304-b6ea-9dc5f8409360)

**Comment by JeffDropsIT** [comment]
@Buhle8 this applies to all services
